const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.Anchor,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.ScriptsInEvents.Ejogo_Event19_Act2,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Anchor: 0},
	{Tilemap2: 0},
	{Solid: 0},
	{Tilemap: 0},
	{Tilemap3: 0},
	{Keyboard: 0},
	{Tilemap4: 0},
	{Vida2: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{bruxinha: 0},
	{direção: 0},
	{Plataforma: 0},
	{inimigo: 0},
	{direita: 0},
	{esquerda: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Âncora: 0},
	{vida: 0},
	{Audio: 0},
	{Sprite: 0},
	{Text: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Mouse: 0},
	{Menu: 0},
	{Sprite2: 0},
	{SpriteFont: 0},
	{Tilemap5: 0},
	{Sprite7: 0},
	{Bullet: 0},
	{magia: 0},
	{Portal: 0},
	{Portal1: 0},
	{Portal2: 0},
	{Text2: 0},
	{SpriteFont2: 0},
	{Text3: 0},
	{jogar: 0},
	{Sprite6: 0}
];

self.InstanceType = {
	Tilemap2: class extends self.ITilemapInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Tilemap3: class extends self.ITilemapInstance {},
	Keyboard: class extends self.IInstance {},
	Tilemap4: class extends self.ITilemapInstance {},
	bruxinha: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	direita: class extends self.ISpriteInstance {},
	esquerda: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	vida: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Menu: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Tilemap5: class extends self.ITilemapInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	magia: class extends self.ISpriteInstance {},
	Portal1: class extends self.ISpriteInstance {},
	Portal2: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	Text3: class extends self.ITextInstance {},
	jogar: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {}
}